language: ruby
sudo: false
dist: jammy
rvm:
  - 3.4.4

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - nvm install --lts

before_script:
  - cd ./spec/internal
  - yarn install
  - yarn build:css

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
