language: ruby
sudo: false
dist: jammy
rvm:
  - 3.4.4

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - nvm install --lts

before_script:
  - yarn
  - cd ./spec/internal && yarn build:css:compile && yarn build:css:prefix

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
